name: habbo_dart
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Your Name <email@example.com>

environment:
  sdk: '>=1.11.1 <2.0.0'

dependencies:
  postgresql: "^0.3.4+1"

# dev_dependencies:
  # test: ^0.12.0
